# Vehicle Number Plate Recognition System Configuration

# Model paths and settings
models:
  cascade_path: "models/haarcascade_license_plate.xml"
  backup_cascade_path: "models/plate_cascade.xml"

# Detection parameters
detection:
  min_plate_area: 1000
  max_plate_area: 50000
  aspect_ratio_min: 2.0
  aspect_ratio_max: 6.0
  scale_factor: 1.1
  min_neighbors: 5

# Recognition parameters
recognition:
  confidence_threshold: 0.6
  languages: ["en"]
  gpu_enabled: false
  ocr_engine: "easyocr"

# Image processing settings
processing:
  max_dimension: 1200
  enhance_contrast: true
  noise_reduction: true
  clahe_clip_limit: 3.0
  clahe_tile_grid_size: [8, 8]

# Output settings
output:
  save_detected_plates: true
  save_annotated_images: true
  export_formats: ["json", "csv"]
  
# Logging
logging:
  level: "INFO"
  file: "logs/vnpr.log"
  max_size: "10MB"
  backup_count: 5
